[package]
name = "eink-info-display"
version = "0.1.0"
authors = ["Jack H. <jack@jackhil.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysfs_gpio = "0.5"
spidev = "0.4.0"
image = "0.23.4"
